---
title: "About"
---

# I am a ...

## [**Math Enthusiast**]{.underline}

"Math enthusiast" is the term I use to describe myself to my students. I hope to transfer my enthusiasm about math to them; I believe my impression of math is transferable and can help students build positive associations with mathematics.

## [**Classical Musician**]{.underline}

I am a classically trained musician; I started playing the piano at the age of 4 and the viola at the age of 19. I sometimes perform as a soloist or as a chamber musician. Classical music always makes my life a lot richer and more fulfilling.

## [**Harm Reduction Worker**]{.underline}

I work as a harm-reduction worker at a local shelter in Waterloo, ON. Harm reduction saves lives!!

## [**Researcher**]{.underline}

My research interests include:

-   Designing Accessible K-12 Mathematics Curriculum
-   Reasoning & Decision-Making Processes in Mathematical Learning
-   Examining the Roles of Self-esteem and Self-efficacy of Students in Learning Mathematics
-   Teacher Education: Transferable Impressions of Mathematics
-   Supporting Students with Various Learning Needs in Mathematics Education
-   The Role of Harm-Reduction in Addiction Treatment
-   Sense of Belonging in Children and Adolescents
-   Education for People with Neurodevelopmental Conditions
-   Importance of Lived/living Experiences in Treating Mood Disorders
-   Youth Homelessness

This is not an exhaustive list.

## [**Trans Activist**]{.underline}

I am a racialized trans/non-binary person. Supporting and advocating for the trans\* community in various ways are essential parts of my life. If you are a queer/trans person and wish to talk more about navigating your school/work safely as a queer/trans person, please feel free to reach me.
