---
title: "My Journey of Learning English as a Second Language"
---

When I first moved to Canada at age 13, I only knew minimal English and was assigned to the lowest level ESL (English as a Second Language) class.

## Learning English through Social Interactions

I am the person who always search for meaningful interactions with people that I care for. The way I learned English was constantly searching for connections. I joined many 2SLGBTQ+ youth groups to play board games with, to go on field trips, and to learn from each other. I volunteered at a culinary arts program and at a healthcare centre. I attended so many school events for newcomers, and I also volunteered as a peer leader at the newcomer orientation program. Since everyone at the newcomer program was a newcomer, they were more understanding of my language barrier and tried to speak in the way I could understand better. Learning from other newcomers really helped me learn English quickly. I passed 4 ESL levels within one year of study in Canada, and I moved on to taking regular academic English with native speaking peers.

Due to the cultural norms, I had never learned how to express my feelings in my native language, Korean. I am a different person when I speak in English. I actively signed myself up for counselling/therapy sessions, and I was also supported by many queer adults around me. I learned so much English from all these conversations I had with people in my circle of care. And, I know how to express myself way better in English as a result.

Now, I rarely need a dictionary to get through my day-to-day life, and I am thankful for all social connections that allowed me to learn English in an optimal way.
