---
title: "My Learning Philosophy"
---

Learning shapes who I am.

When it comes to learning, there are reminders I give myself:

-   Learning is a privilege
-   Everyone deserves to learn
-   Not every learning is visible

I lived at a homeless shelter from age 17 to age 20 because I was not safe at home after coming out as a trans person. As a homeless youth, I faced a lot of other factors that affected my education, which I had never thought of before. I was still a high school student, and I had to go to school. From the shelter to my high school, I had to take 2 buses and 3 trains. I would wake up at 5 am, ask the night staff for the crappy sandwich that they gave out as school lunch, and head to school. Even then, I was still late for my first period which was physics. My physics teacher was upset with me because I was mostly not there. After school, I returned to the shelter as soon as I could because I could not afford to miss the dinner time (otherwise, I would have to fight for food during the night snack time). I did not have time to study because I had to survive through all the violence happening around me (and sometimes targeted at me) at the shelter. In order for me to use the washroom as a trans/nonbinary person, I was forced to ask the shelter staff every time to unlock the single-user washroom. I was really fighting for my human rights when I could simply "just" study.

The second shelter I stayed at was so much better than the first one. They had reliable and quality food, some staff who would advocate for my trans rights, and it was a lot closer to my high school. There, I was able to graduate from high school and apply to universities. They covered my university application fees. This shelter also had a program called Stay In School (SIS), and my undergraduate study was entirely funded by them. I was a resident of SIS until the second year of my undergraduate program. They also connected me with a tutor from UofT, and he really helped me stay interested in math. SIS also supported me to learn how to play the viola, and this musical interest of mine has grown to be an essential part of my well-being.

What I learned from my experience of homelessness are reflected on the above reminders. I want to support other people's experiences of learning through a trauma-informed practice. I dream of a society that learning is not a privilege anymore.
