---
title: "My Journey of Learning Mathematics"
---

I grew up in South Korea until the age of 13 where math is intensively taught. I also want to be clear with my background with math that I have completed my bachelor's degree in Honours Psychology and Joint Honours Mathematics at the University of Waterloo. I am also studying/researching mathematics education at Ontario Tech University for my master's degree. To simplify, I believe learning math has largely three components: understanding the mathematical concepts involved, connecting the new math concepts to already existing math concepts in one's mind, and training through repetitions.

## Learning Math as a Postsecondary Student (Ages 18-22)

I first started my bachelor's degree at the faculty of mathematics at UWaterloo. The following is the list of all math-related courses I have taken during my undergraduate degree:

-   proof-based algebra
-   2 linear algebra courses
-   3 calculus courses (advanced level)
-   intro to combinatorics
-   designing functional programs (advanced level)
-   elementary algorithm design and data abstraction
-   2 statistics
-   3 data analysis courses (basic data analysis, advanced data analysis, data analysis and graphing in R)
-   intro to real analysis
-   elementary number theory
-   directed studies in number theory
-   intro to formal logic

In my second year, I declared the Pure Mathematics major and added the Math Teaching major later on. I loved studying math, especially number theory. I was amazed by the beauty of the prime number theorem and by the applications of roots of unity. I was mathematically challenged to push my limit slightly further each time, and I learned so much from the process. The biggest gains I earned from the experience of studying math at the postsecondary level are resiliency and grit. No matter how hard the problem is, I am always ready to tackle it, and I never give up. However, during my third year, I realized that I would be much happier as a math educator (and as a math education researcher) than as a mathematician. I never felt a sense of belonging in the math faculty; I was always a foreigner in their math classes. I felt like my human-ness was erased in most of my math classes because so many pure math courses were operating without considering the importance of human-math interactions. Many instructors seemed to have forgotten the fact that they are teaching math to "people". Of course, I have seen instructors who genuinely appreciated the human-ness of their math classes. These mathematicians knew how to honour the power and curiosity each student brings to the space, and I consider them as the "frontlines" of postsecondary math education. As a math education researcher, I want to do the research that supports these frontlines to enhance their practices with students.

## Learning Math as a High School Student (Ages 14-17)

I brought all the textbooks for the entire Korean high school math curriculum so I could teach myself during every summer vacation. I also joined Mathletes (contest math preparation club) to study math by preparing for math competitions (For my senior years of high school, I served as a president of Mathletes - teaching math lessons to peers. If you are interested in my teaching experiences there, please visit the "Teaching Mathematics" section of my blog). With intensive training in math, I was consistently one of the top-performing students in many Canada-wide math competitions. During my high school years, I was very lucky to meet AF, who became one of my greatest inspirations for studying math later on. His passion for math transferred to me well and motivated me to learn more mathematics. He was the vice president of Mathletes and was the first person to introduce me to the postsecondary level of mathematics. I still use the books that he recommended when I teach my own students advanced mathematics.

## Learning Math as a Middle School Student (Ages 12-13)

The first thing that my grade 7 math teacher did was to administer a quiz to test how much of middle school math we knew. Yes, I said middle school math. We were tested on materials that we had not been taught. The teacher expected many of us to know middle school math already, which was actually the case for some of my friends. One of my friends started learning calculus in grade 5. At this point of my life, I had never studied ahead of the standard curriculum - so I remember not knowing how to deal with negative integers on that quiz. It turned out that I scored 79% on my first math exam in middle school. I quickly learned that I would not be successful in math exams if I did not take action at that point. My mother placed me in a math tutoring centre, and I was semi-forced into studying mathematics for 15-20 hours daily. For any other math exams after the first one, I got 100% - this was a forever game changer. Grades were a huge motivator for me. I thought I could do anything I wanted if I tried hard enough. Then... I moved to Toronto as I turned 14.

## Learning Math as an Elementary School Student (Ages 6-11)

I was never particularly strong in math in my elementary school years. Since my birthday is Dec 31, I was one of the youngest children in my grade. I was smaller and slower than other kids in my class until grade 3 (age 8). I still remember my summer vacation of the second grade being taken away because I could not memorize the $9 \times 9$ table backward in one minute.
