---
title: "My Journey of Teaching Piano"
---

I occasionally teach piano lessons in South Korea.

## Teaching an Adult Piano Learner

It takes a lot more motivation for adults to learn new instruments. The worst thing that a music teacher can do is obstructing that motivation. Many of them *choose* to learn music to have fun and to construct a fulfilling life. Hence, it needs to stay that way. To support an adult learner's musical journey effectively, teachers need to be attentive to their goals, honouring their autonomy. Teachers should be careful about imposing their own goals to their adult students because that might turn off the motivation.

## Teaching a Child Piano Learner

I have taught children as young as 3-year-old. With children at this age, one of the first jobs that a piano teacher does is to teach them how to distinguish their left and right hands. We also teach them how to count up to 5, if they have not learned that yet. Then we number each finger, starting at the thumb, and locate their right thumb at the middle C, and so on. Hence, they do not have any advantages over adult learners when they just start to learn the piano. Since they have less references/knowledge which they already know from their lives to make connections with music, they need to learn everything from the bottom. However, after this "catching up on prior knowledge" period, children have absolute advantages over adults with their rapidly developing brains. They quickly adapt to the fact that they have to play different notes on each hand without even thinking about it. Another factor that they have an advantage over adult learners is their musicality, meaning how they experience and express music. A child's musicality is usually much more multidimensional than musicality of someone who started learning the same instrument as an adult. I believe there is a critical period for obtaining musicality, just like for learning a language.
